#! /bin/sh

# fbpid=$!
idesk &
# sleep 1
feh --bg-scale /run/current-system/profile/share/backgrounds/systole/Systole_Magnet_base_1280_1024.png &
conky &
# wait $fbpid

# X11 set output to preferred
xrandr --auto &

